In [1]:
# import library
import os
import random
import pandas as pd
import numpy as np

In [33]:
#import os
#import zipfile# name of the zip file you want to unzip
#local_zip = 'Users/anikaryadav2002/tlvmc-parkinsons-freezing-gait-prediction.zip'# opening a file with mode parameter 'r' : read existing file
#zip_ref = zipfile.ZipFile(local_zip, 'r')# extract all contents of the zip file
#zip_ref.extractall('')# close the file
#zip_ref.close()

## Pre-processing (DEFOG)🏡

In [2]:
#reference: https://www.kaggle.com/code/ghrangel/read-data-and-merge

DATA_ROOT_DEFOG = 'train/defog'
defog = pd.DataFrame()
for root, dirs, files in os.walk(DATA_ROOT_DEFOG):
    for name in files:       
        f = os.path.join(root, name)
        df_list= pd.read_csv(f)
        df_list['file']= name.split('.')[0]
        defog = pd.concat([defog, df_list], axis=0)

defog

## This file was auto generated by the Azure Machine Learning Studio. Please do not remove.   \
0       ## Read more about the .amlignore file here: h...                                             
1                                .ipynb_aml_checkpoints/                                              
2                                               *.amltmp                                              
3                                               *.amltemp                                             
0       ## Read more about the .amlignore file here: h...                                             
...                                                   ...                                             
120027                                                NaN                                             
120028                                                NaN                                             
120029                                                NaN                                             
120030                                                NaN                                             
120031                                                NaN                                             

              file      Time      AccV     AccML     AccAP  StartHesitation  \
0                        NaN       NaN       NaN       NaN              NaN   
1                        NaN       NaN       NaN       NaN              NaN   
2                        NaN       NaN       NaN       NaN              NaN   
3                        NaN       NaN       NaN       NaN              NaN   
0                        NaN       NaN       NaN       NaN              NaN   
...            ...       ...       ...       ...       ...              ...   
120027  f9fc61ce85  120027.0 -0.962333  0.113288 -0.328300              0.0   
120028  f9fc61ce85  120028.0 -0.962351  0.109235 -0.324841              0.0   
120029  f9fc61ce85  120029.0 -0.956052  0.101676 -0.324484              0.0   
120030  f9fc61ce85  120030.0 -0.951245  0.097876 -0.322607              0.0   
120031  f9fc61ce85  120031.0 -0.949085  0.097475 -0.320794              0.0   

        Turn  Walking  Valid   Task  
0        NaN      NaN    NaN    NaN  
1        NaN      NaN    NaN    NaN  
2        NaN      NaN    NaN    NaN  
3        NaN      NaN    NaN    NaN  
0        NaN      NaN    NaN    NaN  
...      ...      ...    ...    ...  
120027   0.0      0.0  False  False  
120028   0.0      0.0  False  False  
120029   0.0      0.0  False  False  
120030   0.0      0.0  False  False  
120031   0.0      0.0  False  False  

[13525710 rows x 11 columns]

In [3]:
defog = defog[(defog['Task']==1)&(defog['Valid']==1)]

In [4]:
print('the shape of defog dataset is {}'.format(defog.shape))

the shape of defog dataset is (4090530, 11)


##  Combining it with 🏡defog-metadata.

In [5]:
defog_metadata = pd.read_csv("defog_metadata.csv")
defog_metadata

Id Subject  Visit Medication
0    02ab235146  e1f62e      2         on
1    02ea782681  ae2d35      2         on
2    06414383cf  8c1f5e      2        off
3    092b4c1819  2874c5      1        off
4    0a900ed8a2  0e3d49      2         on
..          ...     ...    ...        ...
132  f3a921edee  1a778d      1        off
133  f40e8c6ebe  575c60      1        off
134  f8ddbdd98d  107712      1         on
135  f9efef91fb  5d9cae      2        off
136  f9fc61ce85  040587      1         on

[137 rows x 4 columns]

In [6]:
defog_m= defog_metadata.merge(defog, how = 'inner', left_on = 'Id', right_on = 'file')
defog_m.drop(['file','Valid','Task'], axis = 1, inplace = True)
defog_m

Id Subject  Visit Medication  \
0        02ea782681  ae2d35      2         on   
1        02ea782681  ae2d35      2         on   
2        02ea782681  ae2d35      2         on   
3        02ea782681  ae2d35      2         on   
4        02ea782681  ae2d35      2         on   
...             ...     ...    ...        ...   
4090525  f9fc61ce85  040587      1         on   
4090526  f9fc61ce85  040587      1         on   
4090527  f9fc61ce85  040587      1         on   
4090528  f9fc61ce85  040587      1         on   
4090529  f9fc61ce85  040587      1         on   

        ## This file was auto generated by the Azure Machine Learning Studio. Please do not remove.   \
0                                                      NaN                                             
1                                                      NaN                                             
2                                                      NaN                                             
3                                                      NaN                                             
4                                                      NaN                                             
...                                                    ...                                             
4090525                                                NaN                                             
4090526                                                NaN                                             
4090527                                                NaN                                             
4090528                                                NaN                                             
4090529                                                NaN                                             

             Time      AccV     AccML     AccAP  StartHesitation  Turn  \
0          1000.0 -0.970018  0.061626 -0.265625              0.0   0.0   
1          1001.0 -0.984375  0.044497 -0.265625              0.0   0.0   
2          1002.0 -0.984375  0.029016 -0.265625              0.0   0.0   
3          1003.0 -0.984375  0.015625 -0.265625              0.0   0.0   
4          1004.0 -0.984670  0.015330 -0.265625              0.0   0.0   
...           ...       ...       ...       ...              ...   ...   
4090525  119027.0 -0.961216  0.142428 -0.289655              0.0   0.0   
4090526  119028.0 -0.960343  0.142836 -0.290506              0.0   0.0   
4090527  119029.0 -0.957958  0.145494 -0.290007              0.0   0.0   
4090528  119030.0 -0.960616  0.145839 -0.291527              0.0   0.0   
4090529  119031.0 -0.967076  0.144342 -0.292384              0.0   0.0   

         Walking  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
...          ...  
4090525      0.0  
4090526      0.0  
4090527      0.0  
4090528      0.0  
4090529      0.0  

[4090530 rows x 12 columns]

In [7]:
# summary table function
def summary(df):
    print(f'data shape: {df.shape}')
    summ = pd.DataFrame(df.dtypes, columns=['data type'])
    summ['#missing'] = df.isnull().sum().values * 100
    summ['%missing'] = df.isnull().sum().values / len(df)
    summ['#unique'] = df.nunique().values
    desc = pd.DataFrame(df.describe(include='all').transpose())
    summ['min'] = desc['min'].values
    summ['max'] = desc['max'].values
    summ['first value'] = df.loc[0].values
    summ['second value'] = df.loc[1].values
    summ['third value'] = df.loc[2].values
    
    return summ

In [8]:
summary(defog_m)

data shape: (4090530, 12)


data type   #missing  \
Id                                                    object          0   
Subject                                               object          0   
Visit                                                  int64          0   
Medication                                            object          0   
## This file was auto generated by the Azure Ma...    object  409053000   
Time                                                 float64          0   
AccV                                                 float64          0   
AccML                                                float64          0   
AccAP                                                float64          0   
StartHesitation                                      float64          0   
Turn                                                 float64          0   
Walking                                              float64          0   

                                                    %missing  #unique  \
Id                                                       0.0       91   
Subject                                                  0.0       38   
Visit                                                    0.0        2   
Medication                                               0.0        2   
## This file was auto generated by the Azure Ma...       1.0        0   
Time                                                     0.0   338197   
AccV                                                     0.0  3485229   
AccML                                                    0.0  3539384   
AccAP                                                    0.0  3437121   
StartHesitation                                          0.0        2   
Turn                                                     0.0        2   
Walking                                                  0.0        2   

                                                         min       max  \
Id                                                       NaN       NaN   
Subject                                                  NaN       NaN   
Visit                                                    1.0       2.0   
Medication                                               NaN       NaN   
## This file was auto generated by the Azure Ma...       NaN       NaN   
Time                                                  1000.0  414387.0   
AccV                                               -6.024701  4.458365   
AccML                                              -2.115008  4.524038   
AccAP                                               -5.11865  4.388132   
StartHesitation                                          0.0       1.0   
Turn                                                     0.0       1.0   
Walking                                                  0.0       1.0   

                                                   first value second value  \
Id                                                  02ea782681   02ea782681   
Subject                                                 ae2d35       ae2d35   
Visit                                                        2            2   
Medication                                                  on           on   
## This file was auto generated by the Azure Ma...         NaN          NaN   
Time                                                    1000.0       1001.0   
AccV                                                 -0.970018    -0.984375   
AccML                                                 0.061626     0.044497   
AccAP                                                -0.265625    -0.265625   
StartHesitation                                            0.0          0.0   
Turn                                                       0.0          0.0   
Walking                                                    0.0          0.0   

                                                   third value  
Id                                                  02ea782681  
Subj

In [9]:
defog_m['StartHesitation'].value_counts()

StartHesitation
0.0    4090030
1.0        500
Name: count, dtype: int64

In [10]:
defog_m['Turn'].value_counts()

Turn
0.0    3503701
1.0     586829
Name: count, dtype: int64

In [11]:
defog_m['Walking'].value_counts()

Walking
0.0    3992012
1.0      98518
Name: count, dtype: int64

In [12]:
# garbage collection for memory
import gc
gc.collect()

84

# Feature engineering and modeling (DEFOG)🏡

In [42]:
pip install imblearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 1.8 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [25]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [26]:
conditions = [
    (defog_m['StartHesitation'] == 1),
    (defog_m['Turn'] == 1),
    (defog_m['Walking'] == 1)]
choices = ['StartHesitation', 'Turn', 'Walking']
defog_m['event'] = np.select(conditions, choices, default='Normal')

In [35]:
defog_m['event'].value_counts().to_frame()

count
event                   
Normal           3404683
Turn              586829
Walking            98518
StartHesitation      500

In [36]:
train_df = defog_m[['AccV','AccML','AccAP','event']]

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

train_df['target'] = le.fit_transform(train_df['event'])

In [38]:
X = train_df.drop(['event','target'], axis=1)
y = train_df['target']

In [39]:
X

AccV     AccML     AccAP
0       -0.970018  0.061626 -0.265625
1       -0.984375  0.044497 -0.265625
2       -0.984375  0.029016 -0.265625
3       -0.984375  0.015625 -0.265625
4       -0.984670  0.015330 -0.265625
...           ...       ...       ...
4090525 -0.961216  0.142428 -0.289655
4090526 -0.960343  0.142836 -0.290506
4090527 -0.957958  0.145494 -0.290007
4090528 -0.960616  0.145839 -0.291527
4090529 -0.967076  0.144342 -0.292384

[4090530 rows x 3 columns]

In [40]:
y

0          0
1          0
2          0
3          0
4          0
          ..
4090525    0
4090526    0
4090527    0
4090528    0
4090529    0
Name: target, Length: 4090530, dtype: int64

In [43]:
from imblearn.over_sampling import SMOTE

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Check class distribution before applying SMOTE
print("Class distribution before SMOTE:")
print(y_train.value_counts())

# Find the size of the majority class (Class 0)
majority_class_size = y_train.value_counts().max()

# Apply SMOTE to the training data with sampling_strategy set to the desired ratio
smote = SMOTE(sampling_strategy={1: majority_class_size, 2: majority_class_size, 3: majority_class_size})
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Check class distribution after applying SMOTE
print("\nClass distribution after SMOTE:")
print(pd.Series(y_train_resampled).value_counts())


Class distribution before SMOTE:
target
0    2383356
2     410744
3      68918
1        353
Name: count, dtype: int64

Class distribution after SMOTE:
target
0    2383356
2    2383356
3    2383356
1    2383356
Name: count, dtype: int64


In [22]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier
rf_classifier.fit(X_train_resampled, y_train_resampled)


RandomForestClassifier(random_state=42)

In [62]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  # Import the accuracy_score function

In [24]:
y_pred = rf_classifier.predict(X_test)

In [60]:
def evaluate_metrics(y_true, y_pred):
    
    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred)
    conf_matrix = confusion_matrix(y_true, y_pred)
    classification_rep = classification_report(y_true, y_pred)

    # Print the metrics
    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'Classification Report:\n{classification_rep}')


In [26]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.694083651751729
Confusion Matrix:
[[749843   2934 167278 101272]
 [    63     36     33     15]
 [ 69203    639  92118  14125]
 [ 15408    115   4323   9754]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.73      0.81   1021327
           1       0.01      0.24      0.02       147
           2       0.35      0.52      0.42    176085
           3       0.08      0.33      0.13     29600

    accuracy                           0.69   1227159
   macro avg       0.33      0.46      0.34   1227159
weighted avg       0.80      0.69      0.74   1227159



In [27]:
# Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=42)

# Train the classifier
clf.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = clf.predict(X_test)

In [28]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.6681171714504803
Confusion Matrix:
[[734217   2431 190130  94549]
 [    70     30     35     12]
 [ 82274    530  78538  14743]
 [ 16625     76   5798   7101]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.72      0.79   1021327
           1       0.01      0.20      0.02       147
           2       0.29      0.45      0.35    176085
           3       0.06      0.24      0.10     29600

    accuracy                           0.67   1227159
   macro avg       0.31      0.40      0.31   1227159
weighted avg       0.78      0.67      0.71   1227159



In [29]:
from sklearn.naive_bayes import GaussianNB

# Initialize the Naive Bayes Classifier
clf = GaussianNB()

# Train the classifier
clf.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = clf.predict(X_test)

In [30]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.20768783833227805
Confusion Matrix:
[[155305 203678 242067 420277]
 [    26     22     51     48]
 [ 11861  23968  78977  61279]
 [  2015   2953   4070  20562]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.15      0.26   1021327
           1       0.00      0.15      0.00       147
           2       0.24      0.45      0.32    176085
           3       0.04      0.69      0.08     29600

    accuracy                           0.21   1227159
   macro avg       0.30      0.36      0.16   1227159
weighted avg       0.80      0.21      0.26   1227159



In [31]:
# XG boost
from xgboost import XGBClassifier

# Initialize the XGBoost classifier
xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
xgb_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = xgb_classifier.predict(X_test)

In [32]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.3587424286502401
Confusion Matrix:
[[319316 131403 254065 316543]
 [     1    105     15     26]
 [ 17256  27917 102453  28459]
 [  2983   3398   4859  18360]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.31      0.47   1021327
           1       0.00      0.71      0.00       147
           2       0.28      0.58      0.38    176085
           3       0.05      0.62      0.09     29600

    accuracy                           0.36   1227159
   macro avg       0.32      0.56      0.24   1227159
weighted avg       0.82      0.36      0.45   1227159



In [33]:
# XG boost
from xgboost import XGBClassifier

# Initialize the XGBoost classifier
xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
xgb_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = xgb_classifier.predict(X_test)

In [34]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.3587424286502401
Confusion Matrix:
[[319316 131403 254065 316543]
 [     1    105     15     26]
 [ 17256  27917 102453  28459]
 [  2983   3398   4859  18360]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.31      0.47   1021327
           1       0.00      0.71      0.00       147
           2       0.28      0.58      0.38    176085
           3       0.05      0.62      0.09     29600

    accuracy                           0.36   1227159
   macro avg       0.32      0.56      0.24   1227159
weighted avg       0.82      0.36      0.45   1227159



In [35]:
# LGBM
from lightgbm import LGBMClassifier

# Initialize the LightGBM classifier
lgbm_classifier = LGBMClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
lgbm_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = lgbm_classifier.predict(X_test)

In [36]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.3814249009297084
Confusion Matrix:
[[347228 120480 248936 304683]
 [     4    105     14     24]
 [ 19570  26587 102397  27531]
 [  3095   3326   4840  18339]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.34      0.50   1021327
           1       0.00      0.71      0.00       147
           2       0.29      0.58      0.38    176085
           3       0.05      0.62      0.10     29600

    accuracy                           0.38   1227159
   macro avg       0.32      0.56      0.25   1227159
weighted avg       0.82      0.38      0.47   1227159



In [37]:
# KNN
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN classifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors (n_neighbors) based on your preference

# Train the classifier
knn_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

In [38]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.6231172977584811
Confusion Matrix:
[[662295   4402 227323 127307]
 [    45     46     42     14]
 [ 63502   1002  93110  18471]
 [ 13825    142   6420   9213]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.65      0.75   1021327
           1       0.01      0.31      0.02       147
           2       0.28      0.53      0.37    176085
           3       0.06      0.31      0.10     29600

    accuracy                           0.62   1227159
   macro avg       0.31      0.45      0.31   1227159
weighted avg       0.79      0.62      0.68   1227159



In [ ]:
# Neural Network
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Assuming you have already defined X_train, X_test, y_train, y_test

# Assuming y_train contains the labels and you want to predict multiple classes
num_classes = len(np.unique(y_train_resampled))

# Convert labels to one-hot encoding
y_train_one_hot = tf.keras.utils.to_categorical(y_train_resampled, num_classes)
y_test_one_hot = tf.keras.utils.to_categorical(y_test, num_classes)

# Initialize the neural network
model = Sequential()

# Add layers to the model
model.add(Dense(128, activation='relu', input_shape=(X_train_resampled.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_resampled
          , y_train_one_hot, epochs=10, batch_size=32, validation_split=0.1, verbose=1)

# Make predictions on the test set
y_pred_one_hot = model.predict(X_test)
y_pred = np.argmax(y_pred_one_hot, axis=1)

Epoch 1/10
268128/268128 [==============================] - 860s 3ms/step - loss: 0.8798 - accuracy: 0.6196 - val_loss: 1.3012 - val_accuracy: 0.4174
Epoch 2/10
268128/268128 [==============================] - 857s 3ms/step - loss: 0.8089 - accuracy: 0.6485 - val_loss: 1.3118 - val_accuracy: 0.4510
Epoch 3/10
268128/268128 [==============================] - 852s 3ms/step - loss: 0.7862 - accuracy: 0.6570 - val_loss: 1.3421 - val_accuracy: 0.3734
Epoch 4/10
226657/268128 [========================>.....] - ETA: 1:44:13 - loss: 0.7739 - accuracy: 0.6615

In [ ]:
evaluate_metrics(y_test, y_pred)

In [ ]:
print(y_pred[0:999])

In [ ]:
test_defog_path = '/kaggle/input/tlvmc-parkinsons-freezing-gait-prediction/test/defog/02ab235146.csv'
test_defog = pd.read_csv(test_defog_path)
name = os.path.basename(test_defog_path)
id_value = name.split('.')[0]
test_defog['Id_value'] = id_value
test_defog['Id'] = test_defog['Id_value'].astype(str) + '_' + test_defog['Time'].astype(str)
test_defog = test_defog[['Id','AccV','AccML','AccAP']]
test_defog.set_index('Id',inplace=True)

In [ ]:
# predict event probability
test_defog_pred=rf_classifier.predict(test_defog)
test_defog['event'] = test_defog_pred

In [ ]:
test_defog

In [ ]:
# expand event column it to three columns
test_defog['StartHesitation'] = np.where(test_defog['event']==1, 1, 0)
test_defog['Turn'] = np.where(test_defog['event']==2, 1, 0)
test_defog['Walking'] = np.where(test_defog['event']==3, 1, 0)

In [ ]:
test_defog

In [ ]:
print(test_defog['event'].value_counts(),'\n')
print(test_defog['StartHesitation'].value_counts(),'\n')
print(test_defog['Turn'].value_counts(),'\n')
print(test_defog['Walking'].value_counts(),'\n')

## TDCSFOG🥼

In [44]:
DATA_ROOT_TDCSFOG = 'train/tdcsfog/'
tdcsfog = pd.DataFrame()
for root, dirs, files in os.walk(DATA_ROOT_TDCSFOG):
    for name in files:       
        f = os.path.join(root, name)
        df_list= pd.read_csv(f)
        words = name.split('.')[0]
        df_list['file']= name.split('.')[0]
        tdcsfog = pd.concat([tdcsfog, df_list], axis=0)
tdcsfog

Time      AccV     AccML     AccAP  StartHesitation  Turn  Walking  \
0        0 -9.533939  0.566322 -1.413525                0     0        0   
1        1 -9.536140  0.564137 -1.440621                0     0        0   
2        2 -9.529345  0.561765 -1.429332                0     0        0   
3        3 -9.531239  0.564227 -1.415490                0     0        0   
4        4 -9.540825  0.561854 -1.429471                0     0        0   
...    ...       ...       ...       ...              ...   ...      ...   
4220  4220 -9.403467  0.089003 -3.220304                0     0        0   
4221  4221 -9.404246  0.090531 -3.216584                0     0        0   
4222  4222 -9.405770  0.084380 -3.224039                0     0        0   
4223  4223 -9.403579  0.084236 -3.236686                0     0        0   
4224  4224 -9.405036  0.082027 -3.234458                0     0        0   

            file  
0     003f117e14  
1     003f117e14  
2     003f117e14  
3     003f117e14  
4     003f117e14  
...          ...  
4220  ffda8fadfd  
4221  ffda8fadfd  
4222  ffda8fadfd  
4223  ffda8fadfd  
4224  ffda8fadfd  

[7062672 rows x 8 columns]

In [45]:
##  Combining it with 🥼tdcsfog-metadata.

In [46]:
tdcsfog_metadata = pd.read_csv("tdcsfog_metadata.csv")
tdcsfog_metadata

Id Subject  Visit  Test Medication
0    003f117e14  4dc2f8      3     2         on
1    009ee11563  f62eec      4     2         on
2    011322847a  231c3b      2     2         on
3    01d0fe7266  231c3b      2     1        off
4    024418ba39  fa8764     19     3         on
..          ...     ...    ...   ...        ...
828  feba449e1a  312788     19     1         on
829  ff4f844fd3  af82b2      2     3         on
830  ff53514514  3b2403      2     3         on
831  ff92d9244d  2d57c2     20     2         on
832  ffda8fadfd  7fcee9     20     1        off

[833 rows x 5 columns]

In [47]:
tdcsfog_m= tdcsfog_metadata.merge(tdcsfog, how = 'inner', left_on = 'Id', right_on = 'file')
tdcsfog_m.drop(['file'], axis = 1, inplace = True)
tdcsfog_m

Id Subject  Visit  Test Medication  Time      AccV     AccML  \
0        003f117e14  4dc2f8      3     2         on     0 -9.533939  0.566322   
1        003f117e14  4dc2f8      3     2         on     1 -9.536140  0.564137   
2        003f117e14  4dc2f8      3     2         on     2 -9.529345  0.561765   
3        003f117e14  4dc2f8      3     2         on     3 -9.531239  0.564227   
4        003f117e14  4dc2f8      3     2         on     4 -9.540825  0.561854   
...             ...     ...    ...   ...        ...   ...       ...       ...   
7062667  ffda8fadfd  7fcee9     20     1        off  4220 -9.403467  0.089003   
7062668  ffda8fadfd  7fcee9     20     1        off  4221 -9.404246  0.090531   
7062669  ffda8fadfd  7fcee9     20     1        off  4222 -9.405770  0.084380   
7062670  ffda8fadfd  7fcee9     20     1        off  4223 -9.403579  0.084236   
7062671  ffda8fadfd  7fcee9     20     1        off  4224 -9.405036  0.082027   

            AccAP  StartHesitation  Turn  Walking  
0       -1.413525                0     0        0  
1       -1.440621                0     0        0  
2       -1.429332                0     0        0  
3       -1.415490                0     0        0  
4       -1.429471                0     0        0  
...           ...              ...   ...      ...  
7062667 -3.220304                0     0        0  
7062668 -3.216584                0     0        0  
7062669 -3.224039                0     0        0  
7062670 -3.236686                0     0        0  
7062671 -3.234458                0     0        0  

[7062672 rows x 12 columns]

# Feature engineering and modeling (tdcsDEFOG)🥼

In [48]:
#summary(tdcs_sampled_df)

In [49]:
# garbage collection for memory
import gc
gc.collect()

5009

In [50]:
conditions = [
    (tdcsfog_m['StartHesitation'] == 1),
    (tdcsfog_m['Turn'] == 1),
    (tdcsfog_m['Walking'] == 1)]
choices = ['StartHesitation', 'Turn', 'Walking']
tdcsfog_m['event'] = np.select(conditions, choices, default='Normal')

In [51]:
tdcsfog_m['event'].value_counts()

event
Normal             4871262
Turn               1678782
StartHesitation     304790
Walking             207838
Name: count, dtype: int64

In [52]:
train_df = tdcsfog_m[['AccV','AccML','AccAP','event']]

In [53]:
train_df['target'] = le.fit_transform(train_df['event'])

In [54]:
X = train_df.drop(['event','target'], axis=1)
y = train_df['target']

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier

In [74]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Check class distribution before applying SMOTE
print("Class distribution before SMOTE:")
print(y_train.value_counts())

# Find the size of the majority class (Class 0)
majority_class_size = y_train.value_counts().max()

# Apply SMOTE to the training data with sampling_strategy set to the desired ratio
smote = SMOTE(sampling_strategy={1: majority_class_size, 2: majority_class_size, 3: majority_class_size})
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Check class distribution after applying SMOTE
print("\nClass distribution after SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

Class distribution before SMOTE:
target
0    3410623
2    1174563
1     213256
3     145428
Name: count, dtype: int64

Class distribution after SMOTE:
target
0    3410623
2    3410623
3    3410623
1    3410623
Name: count, dtype: int64


In [64]:
# LGBM
from lightgbm import LGBMClassifier

# Initialize the LightGBM classifier
lgbm_classifier = LGBMClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
lgbm_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_2 = lgbm_classifier.predict(X_test)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030782 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 13642492, number of used features: 3
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294


In [65]:
evaluate_metrics(y_test, y_pred_2)

Accuracy: 0.5318972702498865
Confusion Matrix:
[[857424 227853 291305  84057]
 [  7647  42652  18669  22566]
 [104370 112731 201997  85121]
 [  7729  18449  11320  24912]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.59      0.70   1460639
           1       0.11      0.47      0.17     91534
           2       0.39      0.40      0.39    504219
           3       0.11      0.40      0.18     62410

    accuracy                           0.53   2118802
   macro avg       0.37      0.46      0.36   2118802
weighted avg       0.70      0.53      0.59   2118802



In [70]:
# Random Forest

# Initialize the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier
rf_classifier.fit(X_train_resampled, y_train_resampled)

y_pred = rf_classifier.predict(X_test)

In [71]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.587411659985218
Confusion Matrix:
[[992807 122301 247720  97811]
 [ 18988  30286  24918  17342]
 [162451  73904 204818  63046]
 [ 13817  14403  17492  16698]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.68      0.75   1460639
           1       0.13      0.33      0.18     91534
           2       0.41      0.41      0.41    504219
           3       0.09      0.27      0.13     62410

    accuracy                           0.59   2118802
   macro avg       0.37      0.42      0.37   2118802
weighted avg       0.68      0.59      0.63   2118802



In [ ]:
# Decision tree classifier

# Initialize the Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=42)

# Train the classifier
clf.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = clf.predict(X_test)

In [ ]:
evaluate_metrics(y_test, y_pred)

In [80]:
# Naive Bayes Classifier
# Initialize the Naive Bayes Classifier
clf = GaussianNB()

# Train the classifier
clf.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = clf.predict(X_test)

In [81]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.45116816012067196
Confusion Matrix:
[[789792 284725 275550 110572]
 [ 15069  45851   8421  22193]
 [148853 155855  99840  99671]
 [  9169  25888   6900  20453]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.54      0.65   1460639
           1       0.09      0.50      0.15     91534
           2       0.26      0.20      0.22    504219
           3       0.08      0.33      0.13     62410

    accuracy                           0.45   2118802
   macro avg       0.31      0.39      0.29   2118802
weighted avg       0.63      0.45      0.51   2118802



In [78]:
# XG boost

# Initialize the XGBoost classifier
xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
xgb_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = xgb_classifier.predict(X_test)

In [79]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.531879335586808
Confusion Matrix:
[[860878 229232 288760  81769]
 [  7776  43026  18891  21841]
 [106974 117019 199117  81109]
 [  7888  19017  11579  23926]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.59      0.70   1460639
           1       0.11      0.47      0.17     91534
           2       0.38      0.39      0.39    504219
           3       0.11      0.38      0.18     62410

    accuracy                           0.53   2118802
   macro avg       0.37      0.46      0.36   2118802
weighted avg       0.70      0.53      0.59   2118802



In [86]:
# KNN

# Initialize the KNN classifier
knn_classifier = KNeighborsClassifier(n_neighbors=10)  # You can adjust the number of neighbors (n_neighbors) based on your preference

# Train the classifier
knn_classifier.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

In [85]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.5057456996925621
Confusion Matrix:
[[820025 194876 269900 175838]
 [  9520  38004  20675  23335]
 [104345 109974 192049  97851]
 [  7875  18545  14493  21497]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.56      0.68   1460639
           1       0.11      0.42      0.17     91534
           2       0.39      0.38      0.38    504219
           3       0.07      0.34      0.11     62410

    accuracy                           0.51   2118802
   macro avg       0.36      0.43      0.34   2118802
weighted avg       0.70      0.51      0.57   2118802



In [93]:
X_train_resampled.shape

(13642492, 3)

In [94]:
y_train_resampled.shape

(13642492,)

In [97]:
X_test.shape

(2118802, 3)

In [98]:
y_test.shape

(2118802,)

In [100]:
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Standardize features (you may also consider other scaling methods)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# Reshape the data for LSTM input (samples, time steps, features)
X_train_reshaped = np.reshape(X_train_scaled, (X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_reshaped = np.reshape(X_test_scaled, (X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

# Build the LSTM model
model = Sequential()
model.add(LSTM(50, input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])))
model.add(Dense(1, activation='sigmoid'))  # Adjust the activation function based on your problem

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_reshaped, y_train_resampled, epochs=10, batch_size=32, validation_data=(X_test_reshaped, y_test))

# Evaluate the model
accuracy = model.evaluate(X_test_reshaped, y_test)[1]
print(f"Test Accuracy: {accuracy}")


2023-12-15 11:27:23.991293: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 163709904 exceeds 10% of free system memory.


Epoch 1/10
426328/426328 [==============================] - 824s 2ms/step - loss: -4375.2036 - accuracy: 0.2968 - val_loss: 3246.4485 - val_accuracy: 0.1760
Epoch 2/10
426328/426328 [==============================] - 828s 2ms/step - loss: -13106.0752 - accuracy: 0.2977 - val_loss: 6357.5562 - val_accuracy: 0.1743
Epoch 3/10
426328/426328 [==============================] - 829s 2ms/step - loss: -21845.0508 - accuracy: 0.2973 - val_loss: 9512.6016 - val_accuracy: 0.1807
Epoch 4/10
426328/426328 [==============================] - 825s 2ms/step - loss: -30582.7441 - accuracy: 0.2971 - val_loss: 12718.4062 - val_accuracy: 0.1723
Epoch 5/10
426328/426328 [==============================] - 820s 2ms/step - loss: -39326.3398 - accuracy: 0.2982 - val_loss: 15793.5518 - val_accuracy: 0.1824
Epoch 6/10
426328/426328 [==============================] - 824s 2ms/step - loss: -48101.5898 - accuracy: 0.2987 - val_loss: 18938.5684 - val_accuracy: 0.1848
Epoch 7/10
426328/426328 [========================

In [101]:
evaluate_metrics(y_test, y_pred)

Accuracy: 0.5277255732248696
Confusion Matrix:
[[871315 166988 278376 143960]
 [ 14520  32951  24497  19566]
 [131155  97153 196273  79638]
 [ 10899  16650  17254  17607]]
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.60      0.70   1460639
           1       0.11      0.36      0.16     91534
           2       0.38      0.39      0.38    504219
           3       0.07      0.28      0.11     62410

    accuracy                           0.53   2118802
   macro avg       0.35      0.41      0.34   2118802
weighted avg       0.68      0.53      0.58   2118802



In [95]:
# Check shapes at different steps
print("X_train_resampled shape:", X_train_resampled.shape)
print("y_train shape:", y_train.shape)

# Standardize features
X_train_scaled = scaler.fit_transform(X_train_resampled)
print("X_train_scaled shape:", X_train_scaled.shape)

# Reshape the data for LSTM input
X_train_reshaped = np.reshape(X_train_scaled, (X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
print("X_train_reshaped shape:", X_train_reshaped.shape)

# Double-check shapes of y_train after preprocessing
print("y_train shape (after preprocessing):", y_train.shape)


X_train_resampled shape: (13642492, 3)
y_train shape: (4943870,)
X_train_scaled shape: (13642492, 3)
X_train_reshaped shape: (13642492, 1, 3)
y_train shape (after preprocessing): (4943870,)


In [69]:
test_tdcsfog_path = '003f117e14.csv'
test_tdcsfog = pd.read_csv(test_tdcsfog_path)
name = os.path.basename(test_tdcsfog_path)
id_value = name.split('.')[0]
test_tdcsfog['Id_value'] = id_value
test_tdcsfog['Id'] = test_tdcsfog['Id_value'].astype(str) + '_' + test_tdcsfog['Time'].astype(str)
test_tdcsfog = test_tdcsfog[['Id','AccV','AccML','AccAP']]
test_tdcsfog.set_index('Id',inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: '003f117e14.csv'

In [ ]:
test_tdcsfog

In [ ]:
test_tdcsfog_pred=lgbm_classifier.predict(test_tdcsfog)
test_tdcsfog['event'] = test_tdcsfog_pred

In [ ]:
test_tdcsfog

In [ ]:
test_tdcsfog['StartHesitation'] = np.where(test_tdcsfog['event']==1, 1, 0)
test_tdcsfog['Turn'] = np.where(test_tdcsfog['event']==2, 1, 0)
test_tdcsfog['Walking'] = np.where(test_tdcsfog['event']==3, 1, 0)
test_tdcsfog.reset_index('Id', inplace=True)

In [ ]:
test_tdcsfog

In [ ]:
test_tdcsfog.shape

In [ ]:
print(test_tdcsfog['event'].value_counts(),'\n')
print(test_tdcsfog['StartHesitation'].value_counts(),'\n')
print(test_tdcsfog['Turn'].value_counts(),'\n')
print(test_tdcsfog['Walking'].value_counts(),'\n')

In [177]:
submit = pd.concat([test_tdcsfog,test_defog])
submit = submit[['Id', 'StartHesitation', 'Turn','Walking']]

In [178]:
submit.to_csv('/kaggle/working/submission.csv', index=False)

In [179]:
sample = pd.read_csv('/kaggle/working/submission.csv')